### ISSUE TITLE
Try with email somemailaddress@gmail.club

### ISSUE THREAD

**Issue by madhurtandon** [imotov/elasticsearch-test-scripts#3]
It is not preserving the original form

It is tokenizing to
{
    "tokens": [
        {
            "token": "somemailaddress@gmail.cl",
            "start_offset": 0,
            "end_offset": 24,
            "type": "<EMAIL>",
            "position": 0
        },
        {
            "token": "ub",
            "start_offset": 24,
            "end_offset": 26,
            "type": "<ALPHANUM>",
            "position": 1
        }
    ]
}

**Comment by madhurtandon** [comment]
2.4.6, not upgraded it yet. Will it fix the problem when i upgrade it to latest

**Comment by imotov** [comment]
It's a [known  issue](https://github.com/elastic/elasticsearch/issues/6467). It was [fixed](https://issues.apache.org/jira/browse/LUCENE-5753?filter=-4) in Lucene 7.1, which means it is fixed for elasticsearch 6.0.0 and above.
